[project]
name = "odoo-addons-oca-stock-logistics-reporting"
version = "17.0.20250112.0"
dependencies = [
    "odoo-addon-delivery_line_sale_line_position>=17.0dev,<17.1dev",
    "odoo-addon-stock_move_value_report>=17.0dev,<17.1dev",
    "odoo-addon-stock_picking_comment_template>=17.0dev,<17.1dev",
    "odoo-addon-stock_picking_report_custom_description>=17.0dev,<17.1dev",
    "odoo-addon-stock_picking_report_valued>=17.0dev,<17.1dev",
    "odoo-addon-stock_quantity_history_location>=17.0dev,<17.1dev",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 17.0",
]
